### ISSUE TITLE
open cv 3 isn't needed but is required in cmakelist. 

### ISSUE THREAD

**Issue by Asylbeck** [wavelab/ximea_ros_cam#1]
in line 23 of the Cmakelist: "find_package(OpenCV 3 REQUIRED)"
can be replaced with "find_package(OpenCV REQUIRED)"
the driver still builds and runs ok.  
Checked the header - didn't find any CV3 specific headers.  Installing openCV 3 might be an unnecessary and painful step for driver installation.

**Comment by carloswanguw** [comment]
Okay, I can create a branch for this. For the time being we will use `OpenCV REQUIRED` until there is a need for the new features from `OpenCV 3`

**Comment by carloswanguw** [comment]
Completed this with #5
