### ISSUE TITLE
Add multiple ximea camera support from one launch file

### ISSUE THREAD

**Issue by jskhu** [wavelab/ximea_ros_cam#10]
Unable to launch multiple camera nodes simultaneously within a single launch file. Issues seems to stem from the usb bus being "clogged" by a single camera, resulting in a failure of the other camera nodes.

**Comment by carloswanguw** [comment]
https://github.com/wavelab/ximea_ros_cam/tree/feature-10-multiple_cam_launch will be tackling this issue.

**Comment by carloswanguw** [comment]
Completed
