### ISSUE TITLE
Is a camera calibration file needed?

### ISSUE THREAD

**Issue by MarviB16** [wavelab/ximea_ros_cam#35]
Hello,

i downloaded and build the repo as is. I attached one Ximea camera to the PC, change the serial number in the launch file to the one of my camera, but when i run the code this error occures:

> ... logging to /home/marvin/.ros/log/60b45b78-4fe1-11e9-8a3c-001c4257684d/roslaunch-marvin-Platform-6520.log
> Checking log directory for disk usage. This may take awhile.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://marvin-Platform:41617/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /rosdistro: kinetic
>  * /rosversion: 1.12.14
>  * /ximea_cam/auto_exposure: False
>  * /ximea_cam/auto_exposure_priority: 0.8
>  * /ximea_cam/auto_gain_limit: 2.0
>  * /ximea_cam/auto_time_limit: 30000
>  * /ximea_cam/bw_safetyratio: 1.0
>  * /ximea_cam/calib_file: 
>  * /ximea_cam/calib_mode: False
>  * /ximea_cam/cam_name: ximea_cam
>  * /ximea_cam/cam_trigger_mode: 0
>  * /ximea_cam/data_age_max: 0.1
>  * /ximea_cam/enable_diagnostics: True
>  * /ximea_cam/exposure_time: 6000
>  * /ximea_cam/format: XI_RGB24
>  * /ximea_cam/frame_id: 0
>  * /ximea_cam/frame_rate_control: True
>  * /ximea_cam/frame_rate_set: 10
>  * /ximea_cam/hw_trigger_edge: 0
>  * /ximea_cam/image_directory: /home/dev/
>  * /ximea_cam/image_transport_compressed_format: png
>  * /ximea_cam/image_transport_compressed_jpeg_quality: 100
>  * /ximea_cam/image_transport_compressed_png_level: 5
>  * /ximea_cam/img_capture_timeout: 1000
>  * /ximea_cam/manual_gain: 9
>  * /ximea_cam/num_cams_in_bus: 2
>  * /ximea_cam/poll_time: 2.0
>  * /ximea_cam/poll_time_frame: 0.5
>  * /ximea_cam/pub_frequency: 10.0
>  * /ximea_cam/pub_frequency_tolerance: 1.0
>  * /ximea_cam/publish_xi_image_info: False
>  * /ximea_cam/roi_height: 1024
>  * /ximea_cam/roi_left: 0
>  * /ximea_cam/roi_top: 0
>  * /ximea_cam/roi_width: 1280
>  * /ximea_cam/save_disk: True
>  * /ximea_cam/serial_no: 09654451
>  * /ximea_cam/white_balance_coef_blue: 4.0
>  * /ximea_cam/white_balance_coef_green: 0.0
>  * /ximea_cam/white_balance_coef_red: 3.0
>  * /ximea_cam/white_balance_mode: 2
> 
> NODES
>   /
>     ximea_cam (ximea_ros_cam/ximea_ros_cam_node)
> 
> auto-starting new master
> process[master]: started with pid [6532]
> ROS_MASTER_URI=http://localhost:11311
> 
> setting /run_id to 60b45b78-4fe1-11e9-8a3c-001c4257684d
> process[rosout-1]: started with pid [6548]
> started core service [/rosout]
> process[ximea_cam-2]: started with pid [6565]
> [ INFO] [1553616502.536190404]: Initializing nodelet with 4 worker threads.
> [ INFO] [1553616502.553109300]: Initializing Nodelet ... 
> [ INFO] [1553616502.553148833]: Loading Node Handles ... 
> [ INFO] [1553616502.553160610]: ... Node Handles Loaded. 
> [ INFO] [1553616502.553179107]: Loading Camera Configuration
> [ INFO] [1553616502.554169829]: cam_name: ximea_cam
> [ INFO] [1553616502.555072480]: serial number: 09654451
> [ INFO] [1553616502.555909228]: frame id: 0
> [ INFO] [1553616502.556775238]: calibration file: 
> [ INFO] [1553616502.557614477]: poll_time: 2
> [ INFO] [1553616502.558498119]: poll_time_frame: 0.5
> [ INFO] [1553616502.559291736]: enable_diagnostics: 1
> [ INFO] [1553616502.560097343]: pub_frequency: 10
> [ INFO] [1553616502.560880011]: pub_frequency_tolerance: 1
> [ INFO] [1553616502.561775478]: data_age_max: 0.1
> [ INFO] [1553616502.562771400]: image_transport_compressed_format: png
> [ INFO] [1553616502.563789041]: image_transport_compressed_jpeg_quality: 100
> [ INFO] [1553616502.564953852]: image_transport_compressed_png_level: 5
> [ INFO] [1553616502.565752737]: format: XI_RGB24
> [ INFO] [1553616502.565827716]: format_int: 2
> [ INFO] [1553616502.565850063]: cam_bytesperpixel_: 3
> [ INFO] [1553616502.565861819]: cam_encoding_: bgr8
> [ INFO] [1553616502.566946588]: cam_num_in_bus_: 2
> [ INFO] [1553616502.568116509]: cam_bw_safetyratio_: 1
> [ INFO] [1553616502.569119290]: cam_trigger_mode_: 0
> [ INFO] [1553616502.570151748]: cam_hw_trigger_edge_: 0
> [ INFO] [1553616502.571445722]: cam_framerate_control_: 1
> [ INFO] [1553616502.572716661]: cam_framerate_set_: 10
> [ INFO] [1553616502.573815485]: cam_img_cap_timeout_: 1000
> [ INFO] [1553616502.574911700]: cam_autoexposure_: 0
> [ INFO] [1553616502.576047192]: cam_manualgain_: 9
> [ INFO] [1553616502.577232633]: cam_exposure_time_: 6000
> [ INFO] [1553616502.578572032]: cam_autoexposure_priority_: 0.8
> [ INFO] [1553616502.579779885]: cam_autotime_limit_: 30000
> [ INFO] [1553616502.580754984]: cam_autogain_limit_: 2
> [ INFO] [1553616502.581917722]: cam_white_balance_mode_: 2
> [ INFO] [1553616502.582928440]: cam_white_balance_coef_r_: 3
> [ INFO] [1553616502.584034061]: cam_white_balance_coef_g_: 0
> [ INFO] [1553616502.585317189]: cam_white_balance_coef_b_: 4
> [ INFO] [1553616502.586897517]: cam_roi_left_: 0
> [ INFO] [1553616502.588533371]: cam_roi_top_: 0
> [ INFO] [1553616502.589637220]: cam_roi_width_: 1280
> [ INFO] [1553616502.590643774]: cam_roi_height_: 1024
> [ INFO] [1553616502.628104242]: using default calibration URL
> [ INFO] [1553616502.628157653]: camera calibration URL: file:///home/marvin/.ros/camera_info/ximea_cam.yaml
> [ INFO] [1553616502.628208481]: Unable to open camera calibration file [/home/marvin/.ros/camera_info/ximea_cam.yaml]
> [ WARN] [1553616502.628227573]: Camera calibration file /home/marvin/.ros/camera_info/ximea_cam.yaml not found.
> [ INFO] [1553616502.628660767]: Loading Publishers ... 
> [ INFO] [1553616502.630756247]: publish_xi_image_info: 0
> [ INFO] [1553616502.630797962]: ... Publishers Loaded. 
> [ INFO] [1553616502.630872403]: Loading Timers ... 
> [ INFO] [1553616502.631018554]: xi_open_device_cb_: 0x1
> [ INFO] [1553616502.631068475]: t_frame_cb_: 0x1
> [ INFO] [1553616502.631101153]: ... Timers Loaded.
> [ INFO] [1553616502.631147340]: Loading Image Storage ... 
> [ INFO] [1553616502.632296878]: image_directory: /home/dev/
> [ INFO] [1553616502.633331860]: save_disk: 1
> [ INFO] [1553616502.635006270]: calib_mode_: 0
> [ INFO] [1553616502.635206912]: Shutting down ximea_ros_cam node...
> [ INFO] [1553616502.635246967]: ximea_ros_cam node shutdown complete.
> [ximea_cam-2] process has died [pid 6565, exit code -11, cmd /home/marvin/tmp/devel/lib/ximea_ros_cam/ximea_ros_cam_node __name:=ximea_cam __log:=/home/marvin/.ros/log/60b45b78-4fe1-11e9-8a3c-001c4257684d/ximea_cam-2.log].
> log file: /home/marvin/.ros/log/60b45b78-4fe1-11e9-8a3c-001c4257684d/ximea_cam-2*.log
> 

Does this error occur because i don't have a calibration file?
Thanks!

**Comment by carloswanguw** [comment]
Hi Marvin,

Please change the image_directory parameter to a valid folder (your home folder). This is a known issue that needs to be fixed

**Comment by MarviB16** [comment]
Hi,

i set the image_directory to /home , but the same error still occurs...
You mean the image_directory in the example_cam_config.yaml right?

**Comment by carloswanguw** [comment]
set it to your $HOME directory. type "echo $HOME" in the terminal to see which directory this is.

**Comment by MarviB16** [comment]
Thank you!
