### ISSUE TITLE
Publish to one topic with four cameras

### ISSUE THREAD

**Issue by MarviB16** [wavelab/ximea_ros_cam#38]
Hi,

I am pretty new to ROS, but I currently try to get this working with four cameras, where the image is published to the same topic (ximea_cam/image_raw) with the appropriate header infos (timestamp and frame id).
As i see it the header infos are currently published as i want it, but when i use two or more cameras the topic gets the addition _1 or _2.
Is there a way to disable this?

Thanks!

**Comment by carloswanguw** [comment]
Hi MarviB16,

You can edit the multiple_cams.launch file and change the names for each node.

The idea is that each camera is its own node and is self-contained. You can, however set the frame_id in the example.yaml file, or have seperate yaml files for each node. The time stamps are automatically populated by each node.

Can you not subscribe to all four cameras and then work with that?

**Comment by carloswanguw** [comment]
Based on how this driver is currently designed, I do not think we can change the names for each node to have the same name without having conflicts from ROS. But you can try, I do not know how ROS will behave (it might just crash on start)

**Comment by carloswanguw** [comment]
This issue is stale, will close it for now.
